name: Tesbenches

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      - name: Install Verilator prerequesites
        run: |
          sudo apt-get install git help2man perl python3 make
          sudo apt-get install g++
          sudo apt-get install libfl2 
          sudo apt-get install libfl-dev 
          sudo apt-get install git autoconf flex bison

      # Install Verilator and Python dependencies
      - name: Install Verilator and Dependencies
        run: |
          sudo apt-get update
          pip install cocotb pytest cocotb-test numpy
          pip install cocotbext-axi
          git clone --recursive https://github.com/verilator/verilator
          unset VERILATOR_ROOT
          cd verilator
          git pull
          git tag
          git checkout stable
          autoconf
          ./configure
          make -j `nproc`
          sudo make install

      # Check versions
      - name: Check software version
        run: |
          verilator --version
      # Run tests in soc_software_edition
      - name: Run Tests in soc_software_edition
        run: |
          cd 2_soc_software_edition/tb
          cd holy_core
          make test.hex
          cd ..
          pytest test_runner.py

      # Run tests in single_cycle_edition
      - name: Run Tests in single_cycle_edition
        run: |
          cd 0_single_cycle_edition/tb
          pytest test_runner.py

      # Run tests in fpga_edition
      - name: Run Tests in fpga_edition
        run: |
          cd 1_fpga_edition/tb
          pytest test_runner.py

